--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/KygekPingTPS
build-by-default: true
branches:
- master
- pm3
projects:
  KygekPingTPS:
    path: ""
    libs:
    - src: thebigcrafter/ktpmpl-cfs/ktpmpl-cfs
      version: ^4.0.0
...
