--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekPingTPS
build-by-default: true
branches:
- master
projects:
  KygekPingTPS:
    path: ""
    libs:
    - src: ifera-mc/UpdateNotifier/UpdateNotifier
      version: ^2.1
...
