--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/KygekPingTPS
build-by-default: true
branches:
- main
- pm3
projects:
  KygekPingTPS:
    path: ""
    libs:
      - src: thebigcrafter/Hydrogen/Hydrogen
        version: ^1.0.0
...
