---
#
#  PLUGIN BY:
#   _    __                  _                                     _
#  | |  / /                 | |                                   | |
#  | | / /                  | |                                   | |
#  | |/ / _   _  ____   ____| | ______ ____   _____ ______   ____ | | __
#  | |\ \| | | |/ __ \ / __ \ |/ /  __/ __ \ / __  | _  _ \ / __ \| |/ /
#  | | \ \ \_| | <__> |  ___/   <| / | <__> | <__| | |\ |\ | <__> |   <
#  |_|  \_\__  |\___  |\____|_|\_\_|  \____^_\___  |_||_||_|\____^_\|\_\
#            | |    | |                          | |
#         ___/ | ___/ |                          | |
#        |____/ |____/                           |_|
#
# KygekPingTPS configuration file
#

# Messages configuration (Leave empty to use default messages)
# Use "{prefix}" to display KygekPingTPS default prefix
# Use "&" as formatting codes
# Use "\n" to break into new line
no-permission: ""
player-not-found: ""
# Use "{tps}" to display server TPS in server-tps
server-tps: ""
# Use "{player}" to display player name or self and "{ping}" to display player's ping in player-ping
player-ping: ""

# Whether to check for plugin updates (Recommended)
check-updates: true

##### DANGER ZONE #####
# Do not change this (Only for internal use)!
config-version: "2.0"
#######################
...
